<center><img src="dog.jpg" width=450></center>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Photo credit: [SeventyFour](https://www.istockphoto.com/en/portfolio/SeventyFour?mediatype=photography)

### What is a database?

Databases store and organize data electronically. The data is housed in objects called tables, with data organized into rows and columns (or records and fields). 

A relational database defines relationships between tables of data inside a database.

Although they can look similar to a spreadsheet, databases can store more data, more securely, and allow multiple users to access the same database.

### Our data

This project will use data from the [Austin Animal Shelter](https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Outcomes/9t4d-g238/data_preview).
In this case, the data is saved to this DataLab workbook as a CSV file, but you'll query it just like you would a database!

Here is copy of the data scription from the Animal Shelter website and what you'd expect to find in the data:

|Column Name|Description|Data Type|
|-----------|-----------|---------|
|`animal_id`|Identifier|Text|
|`name`|Animal name, if provided|Text|
|`datetime`|Date of outcome|Floating Timestamp|
|`monthyear`|Month and year of outcome|Floating Timestamp|
|`date_of_birth`|Animal's date of birth|Floating Timestamp|
|`outcome_type`|Details of the outcome|Text|
|`outcome_subtype`|Additional outcome details|Text|
|`animal_type`|Type of animal|Text|
|`sex_upon_outcome`|Details on whether the animal was neutered or intact|Text|
|`age_upon_outcome`|Age of animal at time of outcome|Text|
|`breed`|Animal breed|Text|
|`color`|Animal color|Text|

### Step 1: Explore the data

Before you dig into the data, it's always a good idea to explore it to see if it is as expected. Does the data match what was outlined above? Try querying the data to view a snapshot of the first 10 rows.

In [1]:
SELECT *
FROM 'animal_shelter.csv'
LIMIT 10;

  animal_id       name  ...                                 breed              color
0   A882831  *Hamilton  ...                Domestic Shorthair Mix        Black/White
1   A794011      Chunk  ...                Domestic Shorthair Mix  Brown Tabby/White
2   A776359      Gizmo  ...               Chihuahua Shorthair Mix        White/Brown
3   A821648       None  ...                               Raccoon               Gray
4   A720371      Moose  ...    Anatol Shepherd/Labrador Retriever               Buff
5   A674754       None  ...                Domestic Shorthair Mix       Orange Tabby
6   A659412   Princess  ...               Chihuahua Shorthair Mix              Brown
7   A814515    Quentin  ...  American Foxhound/Labrador Retriever        White/Brown
8   A902098       None  ...                    Domestic Shorthair         Blue Tabby
9   A860161      *Lalo  ...                    Domestic Shorthair        Brown Tabby

[10 rows x 12 columns]

It's also helpful to understand how big the dataset is. How may rows (or records) are there in this data? Query the file to find out.

In [2]:
SELECT COUNT(*) AS total_rows
FROM 'animal_shelter.csv';

   total_rows
0      169720

Your turn! Can you think of another way to count the rows (or records)?

In [3]:
SELECT COUNT(animal_type) AS count_type
FROM 'animal_shelter.csv';

   count_type
0      169720

### Step 2: Get deeper and answer questions about the data

Let's explore the data further. You're probably curious to know what animals came through this shelter so let's start there. How many different animal types has this shelter taken in?

In [4]:
SELECT COUNT(DISTINCT animal_type) AS unique_type_count
FROM 'animal_shelter.csv';

   unique_type_count
0                  5

Now you know how many different animal types there were, can you also find out some more information? What were those animals and how many were there of each animal type?

In [6]:
SELECT animal_type, COUNT(animal_type) AS count_type
FROM 'animal_shelter.csv'
GROUP BY animal_type;

  animal_type  count_type
0         Dog       92475
1        Bird         858
2       Other        8763
3         Cat       67590
4   Livestock          34

You may have noticed in our first investigation of the data that some animal names were listed as **null**. This means they didn't have a name or their. name is missing from the records for another reason.

Your turn! How many animals don't have a name?

In [12]:
SELECT COUNT(*) AS total_rows
FROM 'animal_shelter.csv'
WHERE name IS NULL;

   total_rows
0       48655

Were the animals without a name all a specific animal type?

In [14]:
SELECT DISTINCT animal_type
FROM 'animal_shelter.csv'
WHERE name IS NULL

  animal_type
0         Dog
1        Bird
2       Other
3         Cat
4   Livestock

In [13]:
SELECT DISTINCT animal_type, COUNT(*) AS count_animals
FROM 'animal_shelter.csv'
WHERE name IS NULL
GROUP BY animal_type;

  animal_type  count_animals
0       Other           7210
1         Cat          26270
2         Dog          14510
3        Bird            636
4   Livestock             29

Livestock and other seem like broad categories. Do we have any more details on those without a name?

In [16]:
SELECT animal_type, breed
FROM 'animal_shelter.csv'
WHERE name IS NULL
	AND animal_type IN ('Other', 'Livestock')
GROUP BY animal_type, breed
ORDER BY animal_type;

    animal_type             breed
0     Livestock               Pig
1     Livestock         Sheep Mix
2     Livestock  Potbelly Pig Mix
3     Livestock             Pygmy
4     Livestock        Goat/Pygmy
..          ...               ...
97        Other    Cottontail Mix
98        Other             Otter
99        Other      Squirrel Mix
100       Other             Skunk
101       Other            Turtle

[102 rows x 2 columns]

### Step 3: It's raining cats and dogs

It's probably safe to say that cats and dogs are the most popular pets. But, what is the most common cat breed this shelter saw?

In [19]:
SELECT breed, COUNT(breed) AS count_breed
FROM 'animal_shelter.csv'
WHERE animal_type IN ('Cat')
GROUP BY breed
ORDER BY count_breed DESC
LIMIT 1;

                    breed  count_breed
0  Domestic Shorthair Mix        34006

What were the most common dog names in 2023?

In [24]:
SELECT name, COUNT(*) AS name_count
FROM 'animal_shelter.csv'
WHERE animal_type = 'Dog'
	AND monthyear LIKE '%2023%'
	AND name IS NOT NULL
GROUP BY name
ORDER BY name_count DESC
LIMIT 5;

    name  name_count
0   Luna          38
1    Max          24
2  Bella          21
3   Milo          17
4  Daisy          17

How many animals were adopted in 2023?

In [26]:
SELECT COUNT(*) AS name_count
FROM 'animal_shelter.csv'
WHERE monthyear LIKE '%2023%'
	AND outcome_type = 'Adoption';

   name_count
0        6634

Your turn! What was the most adopted animal type and breed in 2023?

In [3]:
SELECT animal_type, breed, COUNT(*) AS adopted
FROM 'animal_shelter.csv'
WHERE monthyear LIKE '%2023%'
	AND outcome_type = 'Adoption'
GROUP BY animal_type, breed
ORDER BY adopted DESC
LIMIT 10;

  animal_type                   breed  adopted
0         Cat      Domestic Shorthair     2709
1         Cat  Domestic Shorthair Mix      280
2         Dog                Pit Bull      271
3         Dog  Labrador Retriever Mix      262
4         Cat    Domestic Medium Hair      215
5         Dog            Pit Bull Mix      214
6         Dog     German Shepherd Mix      172
7         Dog         German Shepherd      129
8         Dog      Labrador Retriever      116
9         Cat       Domestic Longhair       83