![](image.jpg)

Humans not only take debts to manage necessities. A country may also take debt to manage its economy. For example, infrastructure spending is one costly ingredient required for a country's citizens to lead comfortable lives. The World Bank is the organization that provides debt to countries.

In this project, you are going to analyze international debt data collected by The World Bank. The dataset contains information about the amount of debt (in USD) owed by developing countries across several categories. You are going to find the answers to the following questions:

- What is the number of distinct countries present in the database?
- What country has the highest amount of debt?
- What country has the lowest amount of repayments?

Below is a description of the table you will be working with:

## `international_debt` table

| Column | Definition | Data Type |
|-|-|-|
|country_name|Name of the country|`varchar`|
|country_code|Code representing the country|`varchar`|
|indicator_name|Description of the debt indicator|`varchar`|
|indicator_code|Code representing the debt indicator|`varchar`|
|debt|Value of the debt indicator for the given country (in current US dollars)|`float`|

You will execute SQL queries to answer three questions, as listed in the instructions.

In [1]:
SELECT *
FROM international_debt
LIMIT 5;

  country_name country_code  ...  indicator_code        debt
0  Afghanistan          AFG  ...  DT.DIS.DLXF.CD  72894453.7
1  Afghanistan          AFG  ...  DT.INT.DLXF.CD  53239440.1
2  Afghanistan          AFG  ...  DT.AMT.BLAT.CD  61739336.9
3  Afghanistan          AFG  ...  DT.DIS.BLAT.CD  49114729.4
4  Afghanistan          AFG  ...  DT.INT.BLAT.CD  39903620.1

[5 rows x 5 columns]

In [2]:
SELECT 
	DISTINCT country_name AS total_distinct_countries
FROM international_debt
ORDER BY country_name;

    total_distinct_countries
0                Afghanistan
1                    Albania
2                    Algeria
3                     Angola
4                    Armenia
..                       ...
119            Venezuela, RB
120                  Vietnam
121              Yemen, Rep.
122                   Zambia
123                 Zimbabwe

[124 rows x 1 columns]

In [3]:
-- num_distinct_countries 
-- Write your query here... 
SELECT 
	COUNT(DISTINCT country_name) AS total_distinct_countries
FROM international_debt;

   total_distinct_countries
0                       124

In [4]:
-- highest_debt_country 
-- Write your query here... 
SELECT 
	country_name,
	SUM(debt) AS total_debt
FROM international_debt
GROUP BY country_name
ORDER BY total_debt DESC
LIMIT 1;

  country_name    total_debt
0        China  2.857935e+11

In [5]:
-- lowest_principal_repayment 
-- Write your query here... 
SELECT 
	country_name,
	indicator_name,
	MIN(debt) AS lowest_repayment
FROM international_debt
WHERE indicator_code = 'DT.AMT.DLXF.CD'
GROUP BY country_name, indicator_name
ORDER BY lowest_repayment ASC
LIMIT 1;

  country_name  ... lowest_repayment
0  Timor-Leste  ...           825000

[1 rows x 3 columns]